add create account page.
cs595-Group8/Store-Website pull request #2
Opened 2022-10-17 23:35 UTC by aalnobel

Added create account page

2022-10-18 02:00 UTC, llisaeva requested changes

2022-10-18 02:00 UTC, llisaeva commented on src/views/CreateAccount.vue
> +                <hr>
No need for a horizontal divider at the bottom of the card:
![image](https://user-images.githubusercontent.com/60904343/196317702-27e301a1-b9a8-4098-8d9e-77634c4fe637.png)

2022-10-18 02:03 UTC, llisaeva requested changes

2022-10-18 02:03 UTC, llisaeva commented on src/views/CreateAccount.vue
> +                            </tr>
Looks great! No need for table, bootstrap has a <b-container> that is much better. It lets you use grids, style them with bootstrap classes, and easy to make them adjustable. Also, there is a much cleaner way to group fields and labels, check my PR **Profile Details page**

2022-10-25 01:11 UTC, Eric-Kobelt approved these changes, later dismissed

2022-11-11 02:23 UTC, closed without merging

2022-11-11 02:24 UTC, jdpoppe commented
Already merged in separate branch